# Generated by Django 3.0.3 on 2020-03-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='post_detail_title',
            field=models.CharField(default='Titile', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='study_material')),
                ('title', models.CharField(max_length=255)),
                ('text_one', models.TextField()),
                ('text_two', models.TextField()),
                ('banner_image', models.ImageField(blank=True, upload_to='study_material')),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('post_category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.PostCategoryType')),
                ('post_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.PostDetail')),
            ],
        ),
    ]
